name = "RiskLabAI"
uuid = "a72881da-fdaa-49c1-8962-99caf4ccfee8"
authors = ["RiskLab AI <research@risklab.ai>"]
version = "0.0.1"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Shuffle = "bf21e494-c40e-4daa-abfb-de5ec0aad010"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeSeries = "9e3dc215-6440-5c97-bce1-76c03772f85e"

[compat]
DataFrames = ">= 1.0"
TimeSeries = ">= 0.13.0"
julia = ">= 1.3"
